name: build and test demo app

on:
  push:
    branches:
      - main
      
permissions: write-all

jobs:
  hello:
    runs-on: ubuntu-latest
    name: Hello
    steps:
      - name: Hello
        run: echo Hello

  test-and-build:
    runs-on: ubuntu-latest
    name: test and build
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: install
        working-directory: ./demo-app
        run: npm ci

      - name: run tests
        working-directory: ./demo-app
        run: npm run test:ci

      - name: build application
        working-directory: ./demo-app
        run: npm run build

      - name: Upload Test Result Files
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ${{ github.workspace }}/**/test_out/**/*
          retention-days: 5
          
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.18.0
        if: always()
        with:
          # NOTE: using trx_files instead of files due to https://github.com/EnricoMi/publish-unit-test-result-action/issues/424
          trx_files: "${{ github.workspace }}/**/*.trx"